### ISSUE TITLE
Command completions do not correctly register

### ISSUE THREAD

**Issue by mworzala** [Archy-X/acf-minestom#1]
The register methods for command completions do not actually register the completion.
This includes the provided command completions (chatcolors, players).

It can be reproduced with:
```java
@CommandAlias("example")
private static class ExampleCommand extends BaseCommand {
    @Default
    @CommandCompletion("%chatcolors")
    public void onCommand(CommandSender sender, String chatColor) {
        sender.sendMessage("Received color: " + chatColor);
    }
}
```
Registered with
```java
MinestomCommandManager commandManager = new MinestomCommandManager();
commandManager.registerCommand(new ExampleCommand());
```

The resulting output is the raw completion (`%chatcolors`) in chat, and a console error about the unregistered replacement:

![Screenshot from 2020-12-31 02-14-13](https://user-images.githubusercontent.com/35708499/103399237-ff9bf100-4b0d-11eb-9c71-44db1c28bcaf.png)
![Screenshot from 2020-12-31 02-14-19](https://user-images.githubusercontent.com/35708499/103399238-0165b480-4b0e-11eb-98a6-b556eda7c41d.png)

**Comment by Archy-X** [comment]
I think you have to use the @ symbol, such as @players

**Comment by mworzala** [comment]
Yep youre right, my bad.
